@url = http://127.0.0.1:8765

POST {{url}}
Content-Type: application/json

{
    "action": "deckNamesAndIds",
    "version": 6
}

###


POST {{url}}
Content-Type: application/json

{
    "action": "requestPermission",
    "version": 6
}

###

POST {{url}}
Content-Type: application/json

{
    "action": "notesInfo",
    "version": 6,
    "params": {
      "notes": [54656776]
    }
}

###

POST {{url}}
Content-Type: application/json

{
    "action": "findNotes",
    "version": 6,
    "params": {
        "query": "deck:\"Python\" and -tag:obsidian:python-collections-parcourir-une-collection"
    }
}

###

POST {{url}}
Content-Type: application/json

{
    "action": "changeDeck",
    "version": 6,
    "params": {
        "cards": [1737565130942],
        "deck": "Tests"
    }
}
